#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Xml.Linq;

namespace ReSharperPlugin.ResXFileCodeGeneratorEx
{
    internal sealed class ResourceEntry
    {
        public string Name  { get; set; } = "";
        public string Value { get; set; } = "";

        /// <summary>null for plain string resources; the CLR type name for everything else.</summary>
        public string? TypeName { get; set; }

        /// <summary>The sanitized C# identifier used as the property / const name.</summary>
        public string PropertyName { get; set; } = "";
    }

    /// <summary>
    /// Platform-agnostic .resx → Designer.cs code generator.
    /// <para>
    /// Output is intentionally kept byte-compatible with the original Visual Studio
    /// <c>ResXFileCodeGeneratorEx</c> custom tool (DMK Software's
    /// <c>StronglyTypedResourceBuilderEx</c> rendered through CodeDom's C# provider),
    /// so that a mixed Rider/VS team regenerating the same <c>.Designer.cs</c> does not
    /// get spurious diffs or compile errors. Uses only BCL types so it runs on every
    /// platform the ReSharper/Rider backend supports.
    /// </para>
    /// </summary>
    internal static class ResXCodeGenerator
    {
        // The version stamped into the GeneratedCodeAttribute by the original VS tool
        // (assembly version of ResXFileCodeGeneratorEx.Common). Kept fixed for parity.
        private const string GeneratorVersion = "2.6.0.0";
        private const string GeneratorTypeName =
            "DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx";

        private const string NL = "\r\n";

        // Doc-comment / comment text — verbatim from StronglyTypedResourceBuilderEx.
        private const string ClassDocComment =
            "A strongly-typed resource class, for looking up localized strings, formatting them, etc.";
        private const string ClassComment1Format =
            "This class was auto-generated by the StronglyTypedResourceBuilderEx class via the {0} custom tool.";
        private const string ClassComment2Format =
            "To add or remove a member, edit your .ResX file then rerun the {0} custom tool or rebuild your VS.NET project.";
        private const string ClassComment3Format =
            "Copyright (c) Dmytro Kryvko 2006-{0} (http://dmytro.kryvko.googlepages.com/)";
        private const string ConstructorCommentFormat = "Initializes a {0} object.";
        private const string InternalSyncObjectPropertyComment = "Thread safe lock object used by this class.";
        private const string ResMgrPropertyComment = "Returns the cached ResourceManager instance used by this class.";
        private const string CulturePropertyComment1 = "Overrides the current thread's CurrentUICulture property for all";
        private const string CulturePropertyComment2 = "resource lookups using this strongly typed resource class.";
        private const string NamesNestedClassDocComment = "Lists all the resource names as constant string fields.";
        private const string ResourceNameFieldCommentFormat = "Stores the resource name '{0}'.";
        private const string StringPropertyComment = "Looks up a localized string similar to '{0}'.";
        private const string NonStringPropertyComment = "Looks up a resource '{0}'.";
        private const string FormatMethodComment = "Formats a localized string similar to '{0}'.";
        private const string ParamCommentStatementFormat = "<param name=\"arg{0}\">An object ({0}) to format.</param>";
        private const string MethodReturnValueComment =
            "<returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>";
        private const string StringTruncatedCommentFormat = "{0} [rest of string was truncated]\";";
        private const int DocCommentLengthThreshold = 0x200;

        // Reserved member names the VS builder refuses to emit a property for.
        private static readonly string[] ReservedNames =
            { "ResourceManager", "Culture", "InternalSyncObject", "ResourceNames" };

        // Exactly the character set the VS builder replaces with '_'.
        private static readonly char[] CharsToReplace =
        {
            ' ', '\x00a0', '.', ',', ';', '|', '~', '@', '#', '%', '^', '&', '*', '+', '-', '/',
            '\\', '<', '>', '?', '[', ']', '(', ')', '{', '}', '"', '\'', ':', '!'
        };

        // ------------------------------------------------------------------
        // Public entry point
        // ------------------------------------------------------------------

        /// <param name="year">
        /// Year stamped into the copyright comment. Defaults to the current year (matching
        /// the VS tool); overridable so tests are deterministic.
        /// </param>
        public static string Generate(
            string  resxContent,
            string  namespaceName,
            string  className,
            bool    isInternal,
            int?    year = null)
        {
            var entries = ParseResX(resxContent);
            return Emit(namespaceName, className, isInternal, entries, year ?? DateTime.Now.Year);
        }

        // ------------------------------------------------------------------
        // Parsing
        // ------------------------------------------------------------------

        private static List<ResourceEntry> ParseResX(string xml)
        {
            var result = new List<ResourceEntry>();
            var root   = XDocument.Parse(xml).Root;
            if (root is null) return result;

            var seen = new HashSet<string>(StringComparer.Ordinal);

            foreach (var el in root.Elements("data"))
            {
                var name = el.Attribute("name")?.Value;

                // Skip type-reference metadata (">>name") and mimetype-ish ("$") entries.
                if (string.IsNullOrEmpty(name) || name!.StartsWith(">>") || name.StartsWith("$"))
                    continue;

                // Reserved members the generated class already defines.
                if (ReservedNames.Any(r => string.Equals(r, name, StringComparison.Ordinal)))
                    continue;

                var propName = VerifyResourceName(name);
                if (propName is null)
                    continue;

                // Collisions after sanitization: keep the first, drop later duplicates.
                if (!seen.Add(propName))
                    continue;

                result.Add(new ResourceEntry
                {
                    Name         = name,
                    Value        = el.Element("value")?.Value ?? "",
                    TypeName     = el.Attribute("type")?.Value,
                    PropertyName = propName,
                });
            }

            // The VS builder emits members sorted by (sanitized) name, case-insensitively.
            result.Sort((a, b) =>
                string.Compare(a.PropertyName, b.PropertyName, StringComparison.InvariantCultureIgnoreCase));
            return result;
        }

        // ------------------------------------------------------------------
        // Emission
        // ------------------------------------------------------------------

        private static string Emit(
            string              namespaceName,
            string              className,
            bool                isInternal,
            List<ResourceEntry> entries,
            int                 year)
        {
            var sb       = new StringBuilder(8192);
            var acc      = isInternal ? "internal" : "public";
            var caller   = isInternal ? "InternalResXFileCodeGeneratorEx" : "ResXFileCodeGeneratorEx";
            var hasNs    = !string.IsNullOrEmpty(namespaceName);
            var baseName = hasNs ? $"{namespaceName}.{className}" : className;

            // class indent (B) and member indent (M)
            var b = hasNs ? 1 : 0;
            var m = b + 1;

            AppendHeader(sb);

            // using + spacing differ subtly between the namespaced and global cases —
            // both reproduced exactly as CodeDom renders them.
            if (hasNs)
            {
                Line(sb, 0, $"namespace {namespaceName} {{");
                Line(sb, 1, "using System;");
                Blank(sb, 1);
                Blank(sb, 1);
            }
            else
            {
                Line(sb, 0, "using System;");
                Blank(sb, 0);
                Blank(sb, 0);
                Blank(sb, 0);
            }

            // ---- class doc, comments, attributes, declaration ----
            DocSummary(sb, b, ClassDocComment);
            Line(sb, b, "// " + string.Format(ClassComment1Format, caller));
            Line(sb, b, "// " + string.Format(ClassComment2Format, caller));
            Line(sb, b, "// " + string.Format(ClassComment3Format, year));
            Line(sb, b, $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{GeneratorTypeName}\", \"{GeneratorVersion}\")]");
            Line(sb, b, "[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]");
            sb.Append("#if !SILVERLIGHT").Append(NL);
            Line(sb, b, "[global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]");
            sb.Append("#endif").Append(NL);
            Line(sb, b, "[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Naming\", \"CA1724:TypeNamesShouldNotMatchNamespaces\")]");
            Line(sb, b, $"{acc} partial class {className} {{");

            // ---- fields ----
            Blank(sb, m);
            Line(sb, m, "private static global::System.Resources.ResourceManager _resourceManager;");
            Blank(sb, m);
            Line(sb, m, "private static object _internalSyncObject;");
            Blank(sb, m);
            Line(sb, m, "private static global::System.Globalization.CultureInfo _resourceCulture;");

            // ---- constructor ----
            Blank(sb, m);
            DocSummary(sb, m, string.Format(ConstructorCommentFormat, className));
            Line(sb, m, "[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\")]");
            Line(sb, m, $"{acc} {className}() {{");
            Line(sb, m, "}");

            EmitInternalSyncObject(sb, m, acc);
            EmitResourceManager(sb, m, acc, className, baseName);
            EmitCulture(sb, m, acc);

            // ---- resource fetching properties (sorted) ----
            foreach (var e in entries)
            {
                if (e.TypeName is null)
                    EmitStringProperty(sb, m, acc, e);
                else
                    EmitObjectProperty(sb, m, acc, e);
            }

            // ---- format methods (string entries with >0 placeholders, sorted) ----
            foreach (var e in entries)
            {
                if (e.TypeName is not null) continue;
                if (!TryCountFormatArgs(e.Value, out var argCount) || argCount <= 0) continue;
                EmitFormatMethod(sb, m, acc, e, argCount);
            }

            // ---- nested ResourceNames class ----
            EmitResourceNames(sb, m, acc, entries);

            // ---- close class (and namespace) ----
            Line(sb, b, "}");
            if (hasNs)
                sb.Append("}").Append(NL);

            return sb.ToString();
        }

        // ------------------------------------------------------------------
        // Member emitters
        // ------------------------------------------------------------------

        private static void EmitInternalSyncObject(StringBuilder sb, int m, string acc)
        {
            Blank(sb, m);
            DocSummary(sb, m, InternalSyncObjectPropertyComment);
            Line(sb, m, $"{acc} static object InternalSyncObject {{");
            Line(sb, m + 1, "get {");
            Line(sb, m + 2, "if (object.ReferenceEquals(_internalSyncObject, null)) {");
            Line(sb, m + 3, "global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);");
            Line(sb, m + 2, "}");
            Line(sb, m + 2, "return _internalSyncObject;");
            Line(sb, m + 1, "}");
            Line(sb, m, "}");
        }

        private static void EmitResourceManager(StringBuilder sb, int m, string acc, string className, string baseName)
        {
            Blank(sb, m);
            DocSummary(sb, m, ResMgrPropertyComment);
            Line(sb, m, "[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]");
            Line(sb, m, $"{acc} static global::System.Resources.ResourceManager ResourceManager {{");
            Line(sb, m + 1, "get {");
            Line(sb, m + 2, "if (object.ReferenceEquals(_resourceManager, null)) {");
            Line(sb, m + 3, "global::System.Threading.Monitor.Enter(InternalSyncObject);");
            Line(sb, m + 3, "try {");
            Line(sb, m + 4, "if (object.ReferenceEquals(_resourceManager, null)) {");
            Line(sb, m + 5, $"global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager(\"{baseName}\", typeof({className}).Assembly));");
            Line(sb, m + 4, "}");
            Line(sb, m + 3, "}");
            Line(sb, m + 3, "finally {");
            Line(sb, m + 4, "global::System.Threading.Monitor.Exit(InternalSyncObject);");
            Line(sb, m + 3, "}");
            Line(sb, m + 2, "}");
            Line(sb, m + 2, "return _resourceManager;");
            Line(sb, m + 1, "}");
            Line(sb, m, "}");
        }

        private static void EmitCulture(StringBuilder sb, int m, string acc)
        {
            Blank(sb, m);
            DocSummary(sb, m, CulturePropertyComment1, CulturePropertyComment2);
            Line(sb, m, "[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]");
            Line(sb, m, $"{acc} static global::System.Globalization.CultureInfo Culture {{");
            Line(sb, m + 1, "get {");
            Line(sb, m + 2, "return _resourceCulture;");
            Line(sb, m + 1, "}");
            Line(sb, m + 1, "set {");
            Line(sb, m + 2, "_resourceCulture = value;");
            Line(sb, m + 1, "}");
            Line(sb, m, "}");
        }

        private static void EmitStringProperty(StringBuilder sb, int m, string acc, ResourceEntry e)
        {
            Blank(sb, m);
            DocSummaryRaw(sb, m, string.Format(StringPropertyComment, DocValue(e.Value)));
            Line(sb, m, $"{acc} static string {e.PropertyName} {{");
            Line(sb, m + 1, "get {");
            Line(sb, m + 2, $"return ResourceManager.GetString(ResourceNames.{e.PropertyName}, _resourceCulture);");
            Line(sb, m + 1, "}");
            Line(sb, m, "}");
        }

        private static void EmitObjectProperty(StringBuilder sb, int m, string acc, ResourceEntry e)
        {
            var (typeText, getter) = ResolveObjectType(e.TypeName!);
            Blank(sb, m);
            DocSummary(sb, m, string.Format(NonStringPropertyComment, e.Name));
            Line(sb, m, $"{acc} static {typeText} {e.PropertyName} {{");
            Line(sb, m + 1, "get {");
            Line(sb, m + 2, $"return (({typeText})({getter}(ResourceNames.{e.PropertyName}, _resourceCulture)));");
            Line(sb, m + 1, "}");
            Line(sb, m, "}");
        }

        private static void EmitFormatMethod(StringBuilder sb, int m, string acc, ResourceEntry e, int argCount)
        {
            var decls = string.Join(", ", Enumerable.Range(0, argCount).Select(n => $"object arg{n}"));
            var refs  = string.Join(", ", Enumerable.Range(0, argCount).Select(n => $"arg{n}"));

            Blank(sb, m);
            DocSummaryRaw(sb, m, string.Format(FormatMethodComment, DocValue(e.Value)));
            for (var n = 0; n < argCount; n++)
                Line(sb, m, "/// " + string.Format(ParamCommentStatementFormat, n));
            Line(sb, m, "/// " + MethodReturnValueComment);
            if (argCount > 3)
                Line(sb, m, "[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Design\", \"CA1025:ReplaceRepetitiveArgumentsWithParamsArray\")]");
            Line(sb, m, $"{acc} static string {e.PropertyName}Format({decls}) {{");
            Line(sb, m + 1, $"return string.Format(_resourceCulture, {e.PropertyName}, {refs});");
            Line(sb, m, "}");
        }

        private static void EmitResourceNames(StringBuilder sb, int m, string acc, List<ResourceEntry> entries)
        {
            Blank(sb, m);
            DocSummary(sb, m, NamesNestedClassDocComment);
            Line(sb, m, $"{acc} class ResourceNames {{");
            foreach (var e in entries)
            {
                Blank(sb, m + 1);
                DocSummary(sb, m + 1, string.Format(ResourceNameFieldCommentFormat, e.Name));
                Line(sb, m + 1, $"{acc} const string {e.PropertyName} = {CSharpStringLiteral(e.Name)};");
            }
            Line(sb, m, "}");
        }

        // ------------------------------------------------------------------
        // Doc-comment helpers
        // ------------------------------------------------------------------

        /// <summary>Emits a /// &lt;summary&gt; block whose body lines need no further escaping.</summary>
        private static void DocSummary(StringBuilder sb, int indent, params string[] lines)
        {
            Line(sb, indent, "/// <summary>");
            foreach (var line in lines)
                Line(sb, indent, "/// " + line);
            Line(sb, indent, "/// </summary>");
        }

        /// <summary>
        /// Emits a /// &lt;summary&gt; whose single body value may already contain embedded
        /// newlines (from a multi-line resource value). Reproduces CodeDom's behaviour:
        /// the first line gets "/// ", every continuation line gets "///" with no space.
        /// </summary>
        private static void DocSummaryRaw(StringBuilder sb, int indent, string body)
        {
            Line(sb, indent, "/// <summary>");

            var pieces = body.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');
            Line(sb, indent, "/// " + pieces[0]);
            for (var i = 1; i < pieces.Length; i++)
                Line(sb, indent, "///" + pieces[i]);

            Line(sb, indent, "/// </summary>");
        }

        /// <summary>Truncates (as the VS tool does) then XML-escapes a resource value for a doc comment.</summary>
        private static string DocValue(string value)
        {
            if (value.Length > DocCommentLengthThreshold)
                value = string.Format(StringTruncatedCommentFormat, value.Substring(0, DocCommentLengthThreshold));
            return SecurityElementEscape(value);
        }

        // ------------------------------------------------------------------
        // Low-level line writers
        // ------------------------------------------------------------------

        private static void Line(StringBuilder sb, int indent, string text) =>
            sb.Append(' ', indent * 4).Append(text).Append(NL);

        private static void Blank(StringBuilder sb, int indent) =>
            sb.Append(' ', indent * 4).Append(NL);

        private static void AppendHeader(StringBuilder sb)
        {
            sb.Append("//------------------------------------------------------------------------------").Append(NL);
            sb.Append("// <auto-generated>").Append(NL);
            sb.Append("//     This code was generated by a tool.").Append(NL);
            sb.Append("//").Append(NL);
            sb.Append("//     Changes to this file may cause incorrect behavior and will be lost if").Append(NL);
            sb.Append("//     the code is regenerated.").Append(NL);
            sb.Append("// </auto-generated>").Append(NL);
            sb.Append("//------------------------------------------------------------------------------").Append(NL);
            sb.Append(NL);
        }

        // ------------------------------------------------------------------
        // Utilities
        // ------------------------------------------------------------------

        /// <summary>
        /// Ported from DMKSoftware.CodeGenerators.Tools.FormatValidator.Parse. Returns the number
        /// of composite-format arguments. Returns false (i.e. "emit no Format method") when the
        /// format string is malformed or its indexes are non-contiguous — matching the VS tool,
        /// which swallows the FormatException and skips the method.
        /// </summary>
        private static bool TryCountFormatArgs(string format, out int count)
        {
            count = 0;
            try
            {
                count = ParseFormat(format);
                return true;
            }
            catch (FormatException)
            {
                return false;
            }
        }

        private static int ParseFormat(string format)
        {
            if (format is null) throw new ArgumentNullException(nameof(format));

            var chars  = format.ToCharArray();
            var cursor = 0;
            var curr   = '\0';
            var indexes = new List<int>();

            while (true)
            {
                while (cursor < chars.Length)
                {
                    curr = chars[cursor];
                    cursor++;
                    if (curr == '}')
                    {
                        if (cursor < chars.Length && chars[cursor] == '}') cursor++;
                        else throw new FormatException();
                    }
                    if (curr == '{')
                    {
                        if (cursor < chars.Length && chars[cursor] == '{') cursor++;
                        else { cursor--; break; }
                    }
                }

                if (cursor == chars.Length)
                {
                    indexes.Sort();
                    for (var i = 0; i < indexes.Count; i++)
                        if (i != indexes[i]) throw new FormatException();
                    return indexes.Count;
                }

                cursor++;
                if (cursor == chars.Length || (curr = chars[cursor]) < '0' || curr > '9')
                    throw new FormatException();

                var index = 0;
                do
                {
                    index = (index * 10) + curr - '0';
                    cursor++;
                    if (cursor == chars.Length) throw new FormatException();
                    curr = chars[cursor];
                }
                while (curr >= '0' && curr <= '9' && index < 1000000);

                if (!indexes.Contains(index)) indexes.Add(index);

                while (cursor < chars.Length && (curr = chars[cursor]) == ' ') cursor++;

                // alignment
                if (curr == ',')
                {
                    cursor++;
                    while (cursor < chars.Length && chars[cursor] == ' ') cursor++;
                    if (cursor == chars.Length) throw new FormatException();
                    curr = chars[cursor];
                    if (curr == '-')
                    {
                        cursor++;
                        if (cursor == chars.Length) throw new FormatException();
                        curr = chars[cursor];
                    }
                    if (curr < '0' || curr > '9') throw new FormatException();
                    var alignment = 0;
                    do
                    {
                        alignment = (alignment * 10) + curr - '0';
                        cursor++;
                        if (cursor == chars.Length) throw new FormatException();
                        curr = chars[cursor];
                    }
                    while (curr >= '0' && curr <= '9' && alignment < 1000000);
                }

                while (cursor < chars.Length && (curr = chars[cursor]) == ' ') cursor++;

                // format specifier
                if (curr == ':')
                {
                    cursor++;
                    while (true)
                    {
                        if (cursor == chars.Length) throw new FormatException();
                        curr = chars[cursor];
                        cursor++;
                        if (curr == '{')
                        {
                            if (cursor < chars.Length && chars[cursor] == '{') cursor++;
                            else throw new FormatException();
                        }
                        else if (curr == '}')
                        {
                            if (cursor < chars.Length && chars[cursor] == '}') cursor++;
                            else { cursor--; break; }
                        }
                    }
                }

                if (curr != '}') throw new FormatException();
                cursor++;
            }
        }

        /// <summary>
        /// Sanitizes a resource name into a C# identifier the same way the VS tool does:
        /// replace the known punctuation set with '_', then guarantee validity. Returns null
        /// if no valid identifier can be produced.
        /// </summary>
        private static string? VerifyResourceName(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;

            var chars = name.ToCharArray();
            for (var i = 0; i < chars.Length; i++)
            {
                var c = chars[i];
                if (Array.IndexOf(CharsToReplace, c) >= 0)
                    chars[i] = '_';
            }

            var sb = new StringBuilder(chars.Length);
            foreach (var c in chars)
                sb.Append(IsValidIdentifierChar(c) ? c : '_');

            var safe = sb.ToString();
            if (safe.Length == 0) return null;

            // Identifiers may not start with a digit.
            if (char.IsDigit(safe[0]))
                safe = "_" + safe;

            return safe;
        }

        private static bool IsValidIdentifierChar(char c) =>
            c == '_' || char.IsLetterOrDigit(c);

        /// <summary>Resolves a resx CLR type name into its C# rendering and the ResourceManager getter.</summary>
        private static (string typeText, string getter) ResolveObjectType(string typeName)
        {
            // "System.Drawing.Bitmap, System.Drawing, Version=..." -> "System.Drawing.Bitmap"
            var simple = typeName.Split(',')[0].Trim();

            if (simple == "System.IO.MemoryStream" || simple == "System.IO.UnmanagedMemoryStream")
                return ("System.IO.UnmanagedMemoryStream", "ResourceManager.GetStream");

            return (CSharpTypeName(simple), "ResourceManager.GetObject");
        }

        /// <summary>Maps CLR type names to their C# keyword form, mirroring CodeDom's primitive handling.</summary>
        private static string CSharpTypeName(string clrName)
        {
            var array = "";
            while (clrName.EndsWith("[]", StringComparison.Ordinal))
            {
                array += "[]";
                clrName = clrName.Substring(0, clrName.Length - 2);
            }

            var mapped = clrName switch
            {
                "System.Boolean" => "bool",
                "System.Byte"    => "byte",
                "System.SByte"   => "sbyte",
                "System.Char"    => "char",
                "System.Decimal" => "decimal",
                "System.Double"  => "double",
                "System.Single"  => "float",
                "System.Int16"   => "short",
                "System.UInt16"  => "ushort",
                "System.Int32"   => "int",
                "System.UInt32"  => "uint",
                "System.Int64"   => "long",
                "System.UInt64"  => "ulong",
                "System.Object"  => "object",
                "System.String"  => "string",
                _ => clrName,
            };

            return mapped + array;
        }

        /// <summary>Reproduces System.Security.SecurityElement.Escape (used by the VS tool for doc values).</summary>
        private static string SecurityElementEscape(string s) =>
            s.Replace("&", "&amp;")
             .Replace("<", "&lt;")
             .Replace(">", "&gt;")
             .Replace("\"", "&quot;")
             .Replace("'", "&apos;");

        /// <summary>Renders a string as a C# double-quoted literal (used for the const field value).</summary>
        private static string CSharpStringLiteral(string s)
        {
            var sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (var c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"':  sb.Append("\\\""); break;
                    case '\r': sb.Append("\\r");  break;
                    case '\n': sb.Append("\\n");  break;
                    case '\t': sb.Append("\\t");  break;
                    default:   sb.Append(c);      break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
